### ISSUE TITLE
possible error in the config file

### ISSUE THREAD

**Issue by yimengli46** [Ram81/habitat-imitation-baselines#2]
Hi, I was trying to run the model on a single node and noticed a misalignment between the model architecture and the shared model weights.

I think the il_objectnav.yaml needs the following two changes.
1. at line 78, change num classes to 29.
2. at line 91, change hidden_size to 2048.

Can you kindly check if the changes are right?

**Comment by Ram81** [comment]
Hi @yimengli46, thanks for pointing out the issue. Yes, you are correct the configs for single node job and multi node jobs are inconsistent. I'll push a fix to the master branch soon.

**Comment by Ram81** [comment]
Hi @yimengli46, I released the fix for inconsistencies between the two config files. You can find the change log in [this commit](https://github.com/Ram81/habitat-imitation-baselines/commit/20efc2e42958c47657549cc05d89b203b41a6efe). Let me know if you are still facing issues after pulling from latest master branch.

**Comment by Ram81** [comment]
Closing this issue. Please reopen the issue if you are still facing the problem.

**Comment by yimengli46** [comment]
Hi Ram, thanks for the response. 

The config file says the rednet_ckpt to use is `rednet_semmap_mp3d_40_v2_vince.pth`.
But the shared link for the semantic segmentation model is `rednet_semmap_mp3d_tuned.pth`.

Can you share the model weights for the second model?
